version: '2'

services:
  postgresql:
    image: bitnami/postgresql:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=stonks
      - POSTGRESQL_PASSWORD=stonks
      - POSTGRESQL_DATABASE=stonks